### ISSUE TITLE
데버런스 기능 TODO List 

### ISSUE THREAD

**Issue by LeeJaeHyeon05** [LeeJaeHyeon05/DevProject#38]
- [x] 사진 업로드 (일단 1개정도)
- [x] 수정
- [x] 태그
- [ ] 알림
- [ ] user 프로필(개인정보수정) 만들기
- [x] 회원가입시 user의 추가 정보 기입 유도하기 (주력 언어, 취직했는지, 원하는 기업 등)
- [ ] 검색 기능 추가
- [x] 정보는 full로 공개하고 특정 기능에 대해 부분 로그인으로 전환
- [ ] 좋아요 기능 및 댓글
- [ ] 프로그래밍 스터디 플랫폼(게시판) 구현

따로 생각이 안 나네요...
넣을 거 있으시면 edit으로 추가해주시면 됩니다!
